/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.Sistema;
import Modelo.Vertice;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Label;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.io.IOException;
import java.util.List;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.DIRECTORIES_ONLY;
import javax.swing.JOptionPane;

/**
 *
 * @author antony
 */
public class GUI extends javax.swing.JFrame{
    private Sistema sys;
    private desenhoGrafo painel;
    private Color cor;
    private RespostaObservable resposta;
    /**
     * Creates new form GUI
     */
    
    public GUI() throws IOException {
        this.sys = new Sistema();
        painel = new desenhoGrafo(sys.getGrafo());
        getContentPane().add(painel);
        pack();                               
        getContentPane().add(painel);
        setLocationRelativeTo(null);                 
        initComponents();          
        this.setSize(1200, 700);
        Label jx = new Label();        
        painel.setLocation(36, painelOpcoes.getY());
        painel.setSize(new Dimension(this.getWidth()-painelOpcoes.getWidth()-106, painelOpcoes.getHeight()));        
        resposta = new RespostaObservable("");
    }

        public class RespostaObservable extends Observable {

        private Object objeto;

        public RespostaObservable(Object objeto) {
            this.objeto = objeto;
        }

        public Object getObjeto() {
            return objeto;
        }

        public void setName(Object objeto) {
            this.objeto = objeto;
            setChanged();
            notifyObservers(objeto);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelOpcoes = new javax.swing.JPanel();
        adicionarVertice = new javax.swing.JButton();
        Botao_sair = new javax.swing.JButton();
        removerVertice = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        arquivo = new javax.swing.JMenu();
        carregarArquivo = new javax.swing.JMenuItem();
        salvarArquivo = new javax.swing.JMenuItem();
        visualizar = new javax.swing.JMenu();
        grafo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WillFall.NET");
        setResizable(false);

        painelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções de Rede"));

        adicionarVertice.setText("Adicionar Equipamento");
        adicionarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarVerticeActionPerformed(evt);
            }
        });

        Botao_sair.setText("Sair");
        Botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_sairActionPerformed(evt);
            }
        });

        removerVertice.setText("Remover Equipamento");
        removerVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerVerticeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelOpcoesLayout = new javax.swing.GroupLayout(painelOpcoes);
        painelOpcoes.setLayout(painelOpcoesLayout);
        painelOpcoesLayout.setHorizontalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOpcoesLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adicionarVertice)
                    .addComponent(Botao_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        painelOpcoesLayout.setVerticalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOpcoesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(adicionarVertice)
                .addGap(18, 18, 18)
                .addComponent(removerVertice)
                .addGap(97, 97, 97)
                .addComponent(Botao_sair)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        arquivo.setText("Arquivo");

        carregarArquivo.setText("Carregar Arquivo");
        carregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarArquivoActionPerformed(evt);
            }
        });
        arquivo.add(carregarArquivo);

        salvarArquivo.setText("Salvar Arquivo");
        salvarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarArquivoActionPerformed(evt);
            }
        });
        arquivo.add(salvarArquivo);

        barraMenu.add(arquivo);

        visualizar.setText("Visualizar");
        barraMenu.add(visualizar);

        grafo.setText("Grafo");
        barraMenu.add(grafo);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(882, Short.MAX_VALUE)
                .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Botao_sairActionPerformed


    private void carregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarArquivoActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        try {
            sys.carregarArquivo(fc.getSelectedFile());
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        painel.repaint();
    }//GEN-LAST:event_carregarArquivoActionPerformed

    private void adicionarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarVerticeActionPerformed
        Object[] opcoes = {"Roteador", "Computador", "Internet"};
        resposta.addObserver(painel.getResposta());
        resposta.setName(JOptionPane.showInputDialog(null, "Selecione qual equipamento deseja adicionar", "adicionar Equipamento", JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]));                      
        painel.adicionarEquipamentoMouse();                  
        painel.repaint();       
    }//GEN-LAST:event_adicionarVerticeActionPerformed

    private void salvarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarArquivoActionPerformed
        JFileChooser fc = new JFileChooser();        
        fc.setDialogTitle("Exportar Arquivo de Configuração");                
        fc.showDialog(this, "Salvar");        
        try {
                sys.salvarArquivo(fc.getSelectedFile().getPath());
        } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }        
        painel.repaint();
        
    }//GEN-LAST:event_salvarArquivoActionPerformed

    private void removerVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerVerticeActionPerformed
        String nome = JOptionPane.showInputDialog("Informe o nome do componente a ser removido").toUpperCase();
        if(sys.removerVertice(nome))
                JOptionPane.showMessageDialog(null, "REMOVIDO COM SUCESSO!!");
        painel.repaint();        
    }//GEN-LAST:event_removerVerticeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_sair;
    private javax.swing.JButton adicionarVertice;
    private javax.swing.JMenu arquivo;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem carregarArquivo;
    private javax.swing.JMenu grafo;
    private javax.swing.JPanel painelOpcoes;
    private javax.swing.JButton removerVertice;
    private javax.swing.JMenuItem salvarArquivo;
    private javax.swing.JMenu visualizar;
    // End of variables declaration//GEN-END:variables

}
